import './globals.css'
import { Inter } from 'next/font/google'
import { SessionProvider } from "./sessionProvider.client"
import { Metadata } from 'next'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

//

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <SessionProvider>
      <html lang="en">
        <body className={inter.className}>
          {children}
        </body>
      </html>
    </SessionProvider>
  )
}
